variable "azure_kubernetes_service" {
    description = "Configuration for Azure Kubernetes Service"
    type = object({
        name                = string
        default_node_pool = object({
            name                          = string
            vm_size                       = string
            capacity_reservation_group_id = optional(string)
            auto_scaling_enabled          = optional(bool, false)
            host_encryption_enabled       = optional(bool)
            node_public_ip_enabled        = optional(bool)
            gpu_instance                  = optional(string)
            host_group_id                 = optional(string)
            fips_enabled                  = optional(bool)
            kubelet_disk_type             = optional(string)
            max_pods                      = optional(number)
            node_public_ip_prefix_id      = optional(string)
            node_labels                   = optional(map(string))
            only_critical_addons_enabled  = optional(string)
            orchestrator_version          = optional(string)
            os_disk_size_gb               = optional(string)
            os_disk_type                  = optional(string)
            os_sku                        = optional(string)
            pod_subnet_id                 = optional(string)
            proximity_placement_group_id  = optional(string)
            scale_down_mode               = optional(string)
            snapshot_id                   = optional(string)
            temporary_name_for_rotation   = optional(string)
            type                          = optional(string, "VirtualMachineScaleSets")
            tags                          = optional(map(string))
            ultra_ssd_enabled             = optional(bool)
            vnet_subnet_key                = optional(string)
            workload_runtime              = optional(string)
            zones                         = optional(list(string))
            max_count                     = optional(number)
            min_count                     = optional(number)
            node_count                    = optional(number)
            kubelet_config = optional(object({
              cpu_manager_policy        = optional(string)
              cpu_cfs_quota_enabled     = optional(bool, true)
              cpu_cfs_quota_period      = optional(string)
              image_gc_high_threshold   = optional(number)
              image_gc_low_threshold    = optional(number)
              topology_manager_policy   = optional(string)
              allowed_unsafe_sysctls    = optional(set(string))
              container_log_max_size_mb = optional(number)
              container_log_max_line    = optional(number)
              pod_max_pid               = optional(number)
            }))
            linux_os_config = optional(object({
              sysctl_config = optional(object({
                fs_aio_max_nr                      = optional(number)
                fs_file_max                        = optional(number)
                fs_inotify_max_user_watches        = optional(number)
                fs_nr_open                         = optional(number)
                kernel_threads_max                 = optional(number)
                net_core_netdev_max_backlog        = optional(number)
                net_core_optmem_max                = optional(number)
                net_core_rmem_default              = optional(number)
                net_core_rmem_max                  = optional(number)
                net_core_somaxconn                 = optional(number)
                net_core_wmem_default              = optional(number)
                net_core_wmem_max                  = optional(number)
                net_ipv4_ip_local_port_range_min   = optional(number)
                net_ipv4_ip_local_port_range_max   = optional(number)
                net_ipv4_neigh_default_gc_thresh1  = optional(number)
                net_ipv4_neigh_default_gc_thresh2  = optional(number)
                net_ipv4_neigh_default_gc_thresh3  = optional(number)
                net_ipv4_tcp_fin_timeout           = optional(number)
                net_ipv4_tcp_keepalive_intvl       = optional(number)
                net_ipv4_tcp_keepalive_probes      = optional(number)
                net_ipv4_tcp_keepalive_time        = optional(number)
                net_ipv4_tcp_max_syn_backlog       = optional(number)
                net_ipv4_tcp_max_tw_buckets        = optional(number)
                net_ipv4_tcp_tw_reuse              = optional(bool)
                net_netfilter_nf_conntrack_buckets = optional(number)
                net_netfilter_nf_conntrack_max     = optional(number)
                vm_max_map_count                   = optional(number)
                vm_swappiness                      = optional(number)
                vm_vfs_cache_pressure              = optional(number)
              }))
        
              transparent_huge_page_enabled = optional(string)
              transparent_huge_page_defrag  = optional(string)
              swap_file_size_mb             = optional(number)
            }))
            node_network_profile = optional(object({
              application_security_group_ids = optional(list(string))
              node_public_ip_tags            = optional(map(string))
              allowed_host_ports = optional(list(object({
                port_end   = optional(number)
                port_start = optional(number)
                protocol   = optional(string)
              })))
            }))
            upgrade_settings = optional(object({
                drain_timeout_in_minutes      = optional(number)
                node_soak_duration_in_minutes = optional(number)
                max_surge                     = string
            }))
        })
        aci_connector_linux_subnet_name = optional(string)
        api_server_access_profile = optional(object({
            authorized_ip_ranges = optional(set(string))
        }))
        auto_scaler_profile = optional(object({
            balance_similar_node_groups                   = optional(string)
            daemonset_eviction_for_empty_nodes_enabled    = optional(string)
            daemonset_eviction_for_occupied_nodes_enabled = optional(string)
            empty_bulk_delete_max                         = optional(string)
            expander                                      = optional(string)
            ignore_daemonsets_utilization_enabled         = optional(string)
            max_graceful_termination_sec                  = optional(string)
            max_node_provisioning_time                    = optional(string)
            max_unready_nodes                             = optional(string)
            max_unready_percentage                        = optional(string)
            new_pod_scale_up_delay                        = optional(string)
            scale_down_delay_after_add                    = optional(string)
            scale_down_delay_after_delete                 = optional(string)
            scale_down_delay_after_failure                = optional(string)
            scale_down_unneeded                           = optional(string)
            scale_down_unready                            = optional(string)
            scale_down_utilization_threshold              = optional(string)
            scan_interval                                 = optional(string)
            skip_nodes_with_local_storage                 = optional(string)
            skip_nodes_with_system_pods                   = optional(string)
        }))
        automatic_upgrade_channel = optional(string)
        azure_active_directory_role_based_access_control = optional(object({
            tenant_id              = optional(string)
            admin_group_object_ids = optional(list(string))
            azure_rbac_enabled     = optional(bool)
        }))
        private_endpoints = optional(map(object({
            subnet_key         = string
            subresource_name   = string
            privatednszone_key = string
        })), {})
        role_assignments = optional(map(object({
            role_definition_id_or_name             = string
            principal_id                           = string
            description                            = optional(string, null)
            skip_service_principal_aad_check       = optional(bool, false)
            condition                              = optional(string, null)
            condition_version                      = optional(string, null)
            delegated_managed_identity_resource_id = optional(string, null)
            principal_type                         = optional(string, null)
        })), {})
        azure_policy_enabled = optional(bool, true)
        cluster_suffix = optional(string, "")
        cost_analysis_enabled = optional(bool, false)
        create_nodepools_before_destroy = optional(bool, false)
        default_nginx_controller = optional(string, "AnnotationControlled")
        defender_log_analytics_workspace_id = optional(string, null)
        disk_encryption_set_id = optional(string, null)
        dns_prefix = optional(string, null)
        dns_prefix_private_cluster = optional(string, null)
        edge_zone = optional(string, null)
        enable_telemetry = optional(bool, true)
        http_application_routing_enabled = optional(bool, false)
        ingress_application_gateway = optional(object({
            gateway_key   = optional(string)
            gateway_name = optional(string)
            subnet_cidr  = optional(string)
            subnet_id    = optional(string)
        }),null)
        managed_identities   = object({
            system_assigned            = optional(bool, false)
            user_assigned_resource_ids = optional(set(string), [])
        })
        http_proxy_config = optional(object({
            http_proxy  = optional(string)
            https_proxy = optional(string)
            no_proxy    = optional(set(string))
            trusted_ca  = optional(string)
        }),null)
        key_management_service = optional(object({
            key_vault_key_id         = string
            key_vault_network_access = string
        }),null)
        key_vault_secrets_provider = optional(object({
            secret_rotation_enabled  = optional(bool)
            secret_rotation_interval = optional(string)
        }),null)
        kubelet_identity = optional(object({
            client_id                 = optional(string)
            object_id                 = optional(string)
            user_assigned_identity_id = optional(string)
        }),null)
        kubernetes_cluster_node_pool_timeouts = optional(object({
            create = optional(string)
            delete = optional(string)
            read   = optional(string)
            update = optional(string)
        }),null)
        kubernetes_cluster_timeouts = optional(object({
            create = optional(string)
            delete = optional(string)
            read   = optional(string)
            update = optional(string)
        }),null)
        kubernetes_version = optional(string, null)
        linux_profile = optional(object({
            admin_username = string
            ssh_key        = string
        }),null)
        local_account_disabled = optional(bool, true)
        lock= optional(object({
            kind = string
            name = optional(string, null)
        }))
        network_profile = optional(object({
            network_plugin      = string
            network_mode        = optional(string)
            network_policy      = optional(string)
            dns_service_ip      = optional(string)
            network_data_plane  = optional(string)
            network_plugin_mode = optional(string)
            outbound_type       = optional(string, "loadBalancer")
            pod_cidr            = optional(string)
            pod_cidrs           = optional(list(string))
            service_cidr        = optional(string)
            service_cidrs       = optional(list(string))
            ip_versions         = optional(list(string))
            load_balancer_sku   = optional(string)
            load_balancer_profile = optional(object({
              managed_outbound_ip_count   = optional(number)
              managed_outbound_ipv6_count = optional(number)
              outbound_ip_address_ids     = optional(list(string))
              outbound_ip_prefix_ids      = optional(list(string))
              outbound_ports_allocated    = optional(number)
              idle_timeout_in_minutes     = optional(number)
            }))
            nat_gateway_profile = optional(object({
              managed_outbound_ip_count = optional(number)
              idle_timeout_in_minutes   = optional(number)
            }))
        }), 
        {
            network_plugin      = "azure"
            network_policy      = "azure"
            network_plugin_mode = "overlay"
        })
        node_os_channel_upgrade = optional(string, "NodeImage")
        node_pools = optional(map(object({
                name                          = string
                vm_size                       = string
                capacity_reservation_group_id = optional(string)
                auto_scaling_enabled          = optional(bool, false)
                max_count                     = optional(number)
                min_count                     = optional(number)
                node_count                    = optional(number)
                host_encryption_enabled       = optional(bool)
                node_public_ip_enabled        = optional(bool)
                eviction_policy               = optional(string)
                host_group_id                 = optional(string)
                fips_enabled                  = optional(bool)
                gpu_instance                  = optional(string)
                kubelet_disk_type             = optional(string)
                max_pods                      = optional(number)
                mode                          = optional(string)
                node_network_profile = optional(object({
                  allowed_host_ports = optional(list(object({
                    port_start = optional(number)
                    port_end   = optional(number)
                    protocol   = optional(string)
                  })))
                  application_security_group_ids = optional(list(string))
                  node_public_ip_tags            = optional(map(string))
                }))
                node_labels                  = optional(map(string))
                node_public_ip_prefix_id     = optional(string)
                node_taints                  = optional(list(string))
                orchestrator_version         = optional(string)
                os_disk_size_gb              = optional(number)
                os_disk_type                 = optional(string)
                os_sku                       = optional(string)
                os_type                      = optional(string)
                pod_subnet_id                = optional(string)
                priority                     = optional(string)
                proximity_placement_group_id = optional(string)
                spot_max_price               = optional(string)
                snapshot_id                  = optional(string)
                tags                         = optional(map(string))
                scale_down_mode              = optional(string)
                ultra_ssd_enabled            = optional(bool)
                vnet_subnet_id               = optional(string)
                zones                        = optional(list(string))
                temporary_name_for_rotation  = optional(string)
                workload_runtime             = optional(string)
                windows_profile = optional(object({
                  outbound_nat_enabled = optional(bool)
                }))
                upgrade_settings = optional(object({
                  drain_timeout_in_minutes      = optional(number)
                  node_soak_duration_in_minutes = optional(number)
                  max_surge                     = string
                }))
            
                kubelet_config = optional(object({
                  cpu_manager_policy        = optional(string)
                  cpu_cfs_quota_enabled     = optional(bool, true)
                  cpu_cfs_quota_period      = optional(string)
                  image_gc_high_threshold   = optional(number)
                  image_gc_low_threshold    = optional(number)
                  topology_manager_policy   = optional(string)
                  allowed_unsafe_sysctls    = optional(set(string))
                  container_log_max_size_mb = optional(number)
                  container_log_max_line    = optional(number)
                  pod_max_pid               = optional(number)
                }))
                linux_os_config = optional(object({
                  sysctl_config = optional(object({
                    fs_aio_max_nr                      = optional(number)
                    fs_file_max                        = optional(number)
                    fs_inotify_max_user_watches        = optional(number)
                    fs_nr_open                         = optional(number)
                    kernel_threads_max                 = optional(number)
                    net_core_netdev_max_backlog        = optional(number)
                    net_core_optmem_max                = optional(number)
                    net_core_rmem_default              = optional(number)
                    net_core_rmem_max                  = optional(number)
                    net_core_somaxconn                 = optional(number)
                    net_core_wmem_default              = optional(number)
                    net_core_wmem_max                  = optional(number)
                    net_ipv4_ip_local_port_range_min   = optional(number)
                    net_ipv4_ip_local_port_range_max   = optional(number)
                    net_ipv4_neigh_default_gc_thresh1  = optional(number)
                    net_ipv4_neigh_default_gc_thresh2  = optional(number)
                    net_ipv4_neigh_default_gc_thresh3  = optional(number)
                    net_ipv4_tcp_fin_timeout           = optional(number)
                    net_ipv4_tcp_keepalive_intvl       = optional(number)
                    net_ipv4_tcp_keepalive_probes      = optional(number)
                    net_ipv4_tcp_keepalive_time        = optional(number)
                    net_ipv4_tcp_max_syn_backlog       = optional(number)
                    net_ipv4_tcp_max_tw_buckets        = optional(number)
                    net_ipv4_tcp_tw_reuse              = optional(bool)
                    net_netfilter_nf_conntrack_buckets = optional(number)
                    net_netfilter_nf_conntrack_max     = optional(number)
                    vm_max_map_count                   = optional(number)
                    vm_swappiness                      = optional(number)
                    vm_vfs_cache_pressure              = optional(number)
                  }))
            }))
        })),{})    
        node_resource_group_name = optional(string, null)  
        oidc_issuer_enabled = optional(bool, false)
        oms_agent = optional(object({
            log_analytics_workspace_id      = string
            msi_auth_for_monitoring_enabled = optional(bool)
        }),null)
        open_service_mesh_enabled = optional(bool, false)
        private_cluster_enabled = optional(bool, false)
        private_cluster_public_fqdn_enabled = optional(bool, false)
        private_dns_zone_key = optional(string, null)
        private_endpoints_manage_dns_zone_group = optional(bool, true)
        role_based_access_control_enabled = optional(bool, true)
        run_command_enabled = optional(bool, false)
        service_principal = optional(object({
            client_id     = string
            client_secret = string
        }),null)
        sku_tier = optional(string, "Standard")
        storage_profile = optional(object({
            blob_driver_enabled         = optional(bool)
            disk_driver_enabled         = optional(bool)
            file_driver_enabled         = optional(bool)
            snapshot_controller_enabled = optional(bool)
        }),null)
        support_plan = optional(string, "KubernetesOfficial")
        tags                          = optional(map(string))
        upgrade_override = optional(object({
            force_upgrade_enabled = bool
            effective_until       = optional(string)
        }),null)
        workload_identity_enabled = optional(bool, false)
        windows_profile = optional(object({
            admin_username = string
            license        = optional(string)
            gmsa = optional(object({
              root_domain = string
              dns_server  = string
            }))
        }),null)
        windows_profile_password = optional(string, null)
        workload_autoscaler_profile = optional(object({
            keda_enabled = optional(bool)
            vpa_enabled  = optional(bool)
        }),null)
        web_app_routing_dns_zone_ids = optional(map(list(string)), {})
    })
}            